version: "3"

services:
    app:
        build: .
        labels:
            - "traefik.enable=true"
            # - "traefik.frontend.rule=Host:ourdomain.com"

    reverse-proxy:
        image: traefik:v1.7
        command: --api --docker.exposedbyDefault=false
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock