name: CI

# Triggers the workflow on push and pull_requests 
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  release:
    types: [ published ]

jobs:        
  test:
    name: Test Modules
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: pwd
            POSTGRES_DB: test
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5000:5432

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v2
        
      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.4

      # Migrate databases
      - name: Pre Test 
        run: DENO_ENV="./.env.test" deno run --allow-env --allow-net --allow-read https://deno.land/x/nessie/cli.ts migrate -c ./src/database/nessie.config.ts 
      
      # Test modules
      - name: Test 
        run: DENO_ENV="./.env.test" deno test --allow-env --allow-read --allow-net 

      # Rollback databases
      - name: Post Test 
        run: DENO_ENV="./.env.test" deno run --allow-env --allow-net --allow-read https://deno.land/x/nessie/cli.ts rollback all -c ./src/database/nessie.config.ts 
