name: CI

# Triggers the workflow on push and pull_requests 
on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop, feature/* ]
  release:
    types: [ published ]

jobs:        
  test:
    name: Test Modules
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v2
        
      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.4

      # Migrate databases
      - name: Pre Test 
        run: DENO_ENV="./.env.test" deno run --allow-env --allow-net --allow-read https://deno.land/x/nessie/cli.ts -d migrate -c ./src/database/nessie.config.ts 
      
      # Test modules
      - name: Test 
        run: DENO_ENV="./.env.test" deno test --allow-env --allow-read --allow-net 

      # Rollback databases
      - name: Post Test 
        run: DENO_ENV="./.env.test" deno run --allow-env --allow-net --allow-read https://deno.land/x/nessie/cli.ts rollback all -c ./src/database/nessie.config.ts 
